// lib/app_data.dart
export 'actividades_data.dart'; // Exporta kActividades

// Lista de 'paises.html' (usada en un <datalist>)
const List<String> kPaises = [
  "AFGANISTÁN",
  "ALAND",
  "ALBANIA",
  "ALEMANIA",
  "ANDORRA",
  "ANGOLA",
  "ANGUILA",
  "ANTÁRTICA",
  "ANTIGUA Y BARBUDA",
  "ARABIA SAUDITA",
  "ARGELIA",
  "ARGENTINA",
  "ARMENIA",
  "ARUBA",
  "AUSTRALIA",
  "AUSTRIA",
  "AZERBAIYÁN",
  "BAHAMAS",
  "BAHREIN",
  "BANGLADESH",
  "BARBADOS",
  "BÉLGICA",
  "BELICE",
  "BENIN",
  "BERMUDAS",
  "BIELORRUSIA",
  "BOLIVIA",
  "BONAIRE, SINT EUSTATIUS AND SABA",
  "BOSNIA-HERZEGOVINA",
  "BOTSWANA",
  "BRASIL",
  "BRUNEI",
  "BULGARIA",
  "BURKINA FASO",
  "BURUNDI",
  "BUTÁN",
  "CABO VERDE",
  "CAIMÁN, ISLAS",
  "CAMBOYA",
  "CAMERÚN",
  "CANADÁ",
  "CENTROAFRICANA, REPÚBLICA",
  "CHAD",
  "CHILE",
  "CHINA",
  "CHIPRE",
  "CIUDAD DEL VATICANO",
  "COLOMBIA",
  "COMORAS",
  "CONGO",
  "COSTA DE MARFIL",
  "COSTA RICA",
  "CROACIA",
  "CUBA",
  "CURAZAO",
  "DINAMARCA",
  "DOMINICA",
  "DJIBOUTÍ",
  "ECUADOR",
  "EGIPTO",
  "EL SALVADOR",
  "EMIRATOS ÁRABES UNIDOS",
  "ERITREA",
  "ESLOVAQUIA",
  "ESLOVENIA",
  "ESPAÑA",
  "ESTADOS UNIDOS",
  "ESTONIA",
  "ETIOPÍA",
  "FIJI",
  "FILIPPINAS",
  "FINLANDIA",
  "FRANCIA",
  "GABÓN",
  "GAMBIA",
  "GEORGIA",
  "GHANA",
  "GIBRALTAR",
  "GRANADA",
  "GRECIA",
  "GROENLANDIA",
  "GUADALUPE",
  "GUAM",
  "GUATEMALA",
  "GUAYANA FRANCESA",
  "GUERNSEY",
  "GUINEA",
  "GUINEA ECUATORIAL",
  "GUINEA-BISSAU",
  "GUYANA",
  "HAITÍ",
  "HONDURAS",
  "HONG KONG",
  "HUNGRÍA",
  "INDIA",
  "INDONESIA",
  "IRAK",
  "IRLANDA",
  "ISLA BOUVET",
  "ISLA DE MAN",
  "ISLA NORFOLK",
  "ISLANDIA",
  "ISLAS NAVIDAD",
  "ISLAS COCOS",
  "ISLAS COOK",
  "ISLAS FAROE",
  "ISLAS GEORGIAS D. S.-SANDWICH D. S.",
  "ISLAS HEARD Y MCDONALD",
  "ISLAS MALVINAS (FALKLAND)",
  "ISLAS MARIANAS DEL NORTE",
  "ISLAS MARSHALL",
  "ISLAS PITCAIRN",
  "ISLAS TURCAS Y CAICOS",
  "ISLAS ULTRAMARINAS DE E.E.U.U",
  "ISLAS VÍRGENES",
  "ISRAEL",
  "ITALIA",
  "JAMAICA",
  "JAPÓN",
  "JERSEY",
  "JORDANIA",
  "KAZAJISTÁN",
  "KENIA",
  "KIRGUISTÁN",
  "KIRIBATI",
  "KUWAIT",
  "LAOS, REPÚBLICA DEMOCRÁTICA",
  "LESOTHO",
  "LETONIA",
  "LÍBANO",
  "LIBERIA",
  "LIBIA",
  "LIECHTENSTEIN",
  "LITUANIA",
  "LUXEMBURGO",
  "MACAO",
  "MACEDONIA",
  "MADAGASCAR",
  "MALASIA",
  "MALAWI",
  "MALDIVAS",
  "MALÍ",
  "MALTA",
  "MARRUECOS",
  "MARTINICA E.A.",
  "MAURICIO",
  "MAURITANIA",
  "MAYOTTE",
  "MÉXICO",
  "MICRONESIA",
  "MOLDAVIA, REPÚBLICA DE",
  "MÓNACO",
  "MONGOLIA",
  "MONTENEGRO",
  "MONTSERRAT",
  "MOZAMBIQUE",
  "MYANMAR",
  "NAMIBIA",
  "NAURU",
  "NEPAL",
  "NICARAGUA",
  "NÍGER",
  "NIGERIA",
  "NIUE",
  "NORUEGA",
  "NUEVA CALEDONIA",
  "NUEVA ZELANDA",
  "OMÁN",
  "PAÍSES BAJOS",
  "PAKISTÁN",
  "PALAOS",
  "PALESTINA",
  "PANAMÁ",
  "PAPÚA, NUEVA GUINEA",
  "PARAGUAY",
  "PERÚ",
  "POLINESIA FRANCESA",
  "POLONIA",
  "PORTUGAL",
  "PUERTO RICO",
  "QATAR",
  "REINO UNIDO",
  "REP. DEMOCRÁTICA POPULAR DE COREA",
  "REPÚBLICA CHECA",
  "REPÚBLICA DE COREA",
  "REPÚBLICA DEMOCRÁTICA DEL CONGO",
  "REPÚBLICA DOMINICANA",
  "REPÚBLICA ISLÁMICA DE IRÁN",
  "REUNIÓN",
  "RUANDA",
  "RUMANIA",
  "RUSIA",
  "SAHARA OCCIDENTAL",
  "SAINT BARTHÉLEMY",
  "SAINT MARTIN (FRENCH PART)",
  "SALOMÓN, ISLAS",
  "SAMOA",
  "SAMOA AMERICANA",
  "SAN CRISTÓBAL Y NIEVES",
  "SAN MARINO",
  "SAN PEDRO Y MIQUELÓN",
  "SAN VICENTE Y LAS GRANADINAS",
  "SANTA ELENA",
  "SANTA LUCÍA",
  "SANTO TOMÉ Y PRÍNCIPE",
  "SENEGAL",
  "SERBIA",
  "SEYCHELLES",
  "SIERRA LEONA",
  "SINGAPUR",
  "SINT MAARTEN (DUTCH PART)",
  "SIRIA",
  "SOMALIA",
  "SOUTH SUDAN",
  "SRI LANKA",
  "SUDÁFRICA",
  "SUDÁN",
  "SUECIA",
  "SUIZA",
  "SURINÁM",
  "SVALBARD Y JAN MAYEN",
  "SWAZILANDIA",
  "TAILANDIA",
  "TAIWAN, PROVINCIA DE CHINA",
  "TANZANIA, REPÚBLICA UNIDA DE",
  "TAYIKISTÁN",
  "TERRITORIO BRITÁNICO OCÉANO INCICO",
  "TERRITORIOS AUSTRALES FRANCESES",
  "TIMOR ORIENTAL",
  "TOGO",
  "TOKELAU",
  "TONGA",
  "TRINIDAD Y TOBAGO",
  "TÚNEZ",
  "TURKMENISTÁN",
  "TURQUÍA",
  "TUVALU",
  "UCRANIA",
  "UGANDA",
  "URUGUAY",
  "UZBEKISTÁN",
  "VANUATU",
  "VENEZUELA",
  "VIETNAM",
  "ISLAS VÍRGENES BRITÁNICAS",
  "WALLIS Y FORTUNA, ISLAS",
  "YEMEN",
  "ZAMBIA",
  "ZIMBABUE",
];

// kActividades movido a actividades_data.dart
// (lista completa con 1006 actividades económicas del Ministerio de Hacienda)

// Mapa de Unidades de Medida (de 'options.html' <select>)
const Map<String, String> kUnidadesMedida = {
  "1": "Metro",
  "2": "Yarda",
  "6": "Milímetro",
  "9": "Kilómetro cuadrado",
  "10": "Hectárea",
  "13": "Metro cuadrado",
  "15": "Vara cuadrada",
  "18": "Metro cúbico",
  "20": "Barril",
  "22": "Galón",
  "23": "Litro",
  "24": "Botella",
  "26": "Mililitro",
  "30": "Tonelada",
  "32": "Quintal",
  "33": "Arroba",
  "34": "Kilogramo",
  "36": "Libra",
  "37": "Onza Troy",
  "38": "Onza",
  "39": "Gramo",
  "40": "Miligramo",
  "42": "Megawatt",
  "43": "Kilowatt",
  "44": "Watt",
  "45": "Megavoltio-amperio",
  "46": "Kilovoltio-amperio",
  "47": "Voltio-amperio",
  "49": "Gigawatt-hora",
  "50": "Megawatt-hora",
  "51": "Kilowatt-hora",
  "52": "Watt-hora",
  "53": "Kilovoltio",
  "54": "Voltio",
  "55": "Millar",
  "56": "Medio millar",
  "57": "Ciento",
  "58": "Docena",
  "59": "Unidad",
  "99": "Otra",
};

// <<< --- INICIO: MAPA DE DEPARTAMENTOS CORREGIDO --- >>>
// Basado 100% en el G_LOCATION_DATA que proporcionaste.
const Map<String, List<String>> kDepartamentosMunicipios = {
  '00 - Otro (Para extranjero)': ['00 - Otro (Para extranjero)'],

  '01 - Ahuachapán': [
    '13 - AHUACHAPAN NORTE',
    '14 - AHUACHAPAN CENTRO',
    '15 - AHUACHAPAN SUR',
  ],
  '02 - Santa Ana': [
    '14 - SANTA ANA NORTE',
    '15 - SANTA ANA CENTRO',
    '16 - SANTA ANA ESTE',
    '17 - SANTA ANA OESTE',
  ],
  '03 - Sonsonate': [
    '17 - SONSONATE NORTE',
    '18 - SONSONATE CENTRO',
    '19 - SONSONATE ESTE',
    '20 - SONSONATE OESTE',
  ],
  '04 - Chalatenango': [
    '34 - CHALATENANGO NORTE',
    '35 - CHALATENANGO CENTRO',
    '36 - CHALATENANGO SUR',
  ],
  '05 - La Libertad': [
    '23 - LA LIBERTAD NORTE',
    '24 - LA LIBERTAD CENTRO',
    '25 - LA LIBERTAD OESTE',
    '26 - LA LIBERTAD ESTE',
    '27 - LA LIBERTAD COSTA',
    '28 - LA LIBERTAD SUR',
  ],
  '06 - San Salvador': [
    '20 - SAN SALVADOR NORTE',
    '21 - SAN SALVADOR OESTE',
    '22 - SAN SALVADOR ESTE',
    '23 - SAN SALVADOR CENTRO',
    '24 - SAN SALVADOR SUR',
  ],
  '07 - Cuscatlán': ['17 - CUSCATLAN NORTE', '18 - CUSCATLAN SUR'],
  '08 - La Paz': [
    '23 - LA PAZ OESTE',
    '24 - LA PAZ CENTRO',
    '25 - LA PAZ ESTE',
  ],
  '09 - Cabañas': ['10 - CABAÑAS OESTE', '11 - CABAÑAS ESTE'],
  '10 - San Vicente': ['14 - SAN VICENTE NORTE', '15 - SAN VICENTE SUR'],
  '11 - Usulután': [
    '24 - USULUTAN NORTE',
    '25 - USULUTAN ESTE',
    '26 - USULUTAN OESTE',
  ],
  '12 - San Miguel': [
    '21 - SAN MIGUEL NORTE',
    '22 - SAN MIGUEL CENTRO',
    '23 - SAN MIGUEL OESTE',
  ],
  '13 - Morazán': ['27 - MORAZAN NORTE', '28 - MORAZAN SUR'],
  '14 - La Unión': ['19 - LA UNION NORTE', '20 - LA UNION SUR'],
};
// <<< --- FIN: MAPA DE DEPARTAMENTOS CORREGIDO --- >>>

// Esta lista se genera automáticamente a partir de las claves del mapa.
final List<String> kDepartamentos = kDepartamentosMunicipios.keys.toList();
