// lib/distritos_data.dart
// Datos de distritos de El Salvador desde https://admin.factura.gob.sv/prod/catalogo/distritos/todos

class Distrito {
  final String codigo;
  final String descripcion;
  final String municipio;
  final String departamento;
  final bool activo;

  const Distrito({
    required this.codigo,
    required this.descripcion,
    required this.municipio,
    required this.departamento,
    required this.activo,
  });

  String get displayName => '$codigo - $descripcion';
}

// Lista completa de distritos de El Salvador
const List<Distrito> kDistritos = [
  Distrito(
    codigo: '09',
    descripcion: 'SAN LORENZO',
    municipio: '13',
    departamento: '01',
    activo: true,
  ),
  Distrito(
    codigo: '03',
    descripcion: 'ATIQUIZAYA',
    municipio: '13',
    departamento: '01',
    activo: true,
  ),
  Distrito(
    codigo: '01',
    descripcion: 'AHUACHAPAN',
    municipio: '14',
    departamento: '01',
    activo: true,
  ),
  Distrito(
    codigo: '30',
    descripcion: 'SN MIG MERCEDES',
    municipio: '36',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '10',
    descripcion: 'SAN PEDRO PUXTLA',
    municipio: '15',
    departamento: '01',
    activo: true,
  ),
  Distrito(
    codigo: '02',
    descripcion: 'APOPA',
    municipio: '21',
    departamento: '06',
    activo: true,
  ),
  Distrito(
    codigo: '13',
    descripcion: 'TEXISTEPEQUE',
    municipio: '14',
    departamento: '02',
    activo: true,
  ),
  Distrito(
    codigo: '06',
    descripcion: 'GUAYMANGO',
    municipio: '15',
    departamento: '01',
    activo: true,
  ),
  Distrito(
    codigo: '04',
    descripcion: 'CONCEPCION DE ATACO',
    municipio: '14',
    departamento: '01',
    activo: true,
  ),
  Distrito(
    codigo: '05',
    descripcion: 'SAN ISIDRO',
    municipio: '10',
    departamento: '09',
    activo: true,
  ),
  Distrito(
    codigo: '08',
    descripcion: 'SAN ANTONIO PAJONAL',
    municipio: '17',
    departamento: '02',
    activo: true,
  ),
  Distrito(
    codigo: '07',
    descripcion: 'ILOPANGO',
    municipio: '22',
    departamento: '06',
    activo: true,
  ),
  Distrito(
    codigo: '05',
    descripcion: 'EL PORVENIR',
    municipio: '17',
    departamento: '02',
    activo: true,
  ),
  Distrito(
    codigo: '07',
    descripcion: 'JUJUTLA',
    municipio: '15',
    departamento: '01',
    activo: true,
  ),
  Distrito(
    codigo: '12',
    descripcion: 'TURIN',
    municipio: '13',
    departamento: '01',
    activo: true,
  ),
  Distrito(
    codigo: '01',
    descripcion: 'ANTGO CUSCATLAN',
    municipio: '26',
    departamento: '05',
    activo: true,
  ),
  Distrito(
    codigo: '29',
    descripcion: 'SAN LUIS CARMEN',
    municipio: '36',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '04',
    descripcion: 'EL CONGO',
    municipio: '16',
    departamento: '02',
    activo: true,
  ),
  Distrito(
    codigo: '09',
    descripcion: 'SAN J GUAYABAL',
    municipio: '17',
    departamento: '07',
    activo: true,
  ),
  Distrito(
    codigo: '01',
    descripcion: 'AGUA CALIENTE',
    municipio: '35',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '05',
    descripcion: 'CHILTIUPAN',
    municipio: '27',
    departamento: '05',
    activo: true,
  ),
  Distrito(
    codigo: '05',
    descripcion: 'EL TRIUNFO',
    municipio: '24',
    departamento: '11',
    activo: true,
  ),
  Distrito(
    codigo: '09',
    descripcion: 'SAN SEBASTIÁN SALITRILLO',
    municipio: '17',
    departamento: '02',
    activo: true,
  ),
  Distrito(
    codigo: '10',
    descripcion: 'EL PARAISO',
    municipio: '35',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '02',
    descripcion: 'APANECA',
    municipio: '14',
    departamento: '01',
    activo: true,
  ),
  Distrito(
    codigo: '33',
    descripcion: 'TEJUTLA',
    municipio: '35',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '05',
    descripcion: 'EL REFUGIO',
    municipio: '13',
    departamento: '01',
    activo: true,
  ),
  Distrito(
    codigo: '08',
    descripcion: 'SAN FRANCISCO MENENDEZ',
    municipio: '15',
    departamento: '01',
    activo: true,
  ),
  Distrito(
    codigo: '01',
    descripcion: 'AGUILARES',
    municipio: '20',
    departamento: '06',
    activo: true,
  ),
  Distrito(
    codigo: '13',
    descripcion: 'LA REINA',
    municipio: '35',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '07',
    descripcion: 'ESTANZUELAS',
    municipio: '24',
    departamento: '11',
    activo: true,
  ),
  Distrito(
    codigo: '05',
    descripcion: 'EL PAISNAL',
    municipio: '20',
    departamento: '06',
    activo: true,
  ),
  Distrito(
    codigo: '06',
    descripcion: 'HUIZUCAR',
    municipio: '26',
    departamento: '05',
    activo: true,
  ),
  Distrito(
    codigo: '03',
    descripcion: 'AYUTUXTEPEQUE',
    municipio: '23',
    departamento: '06',
    activo: true,
  ),
  Distrito(
    codigo: '02',
    descripcion: 'GUACOTECTI',
    municipio: '10',
    departamento: '09',
    activo: true,
  ),
  Distrito(
    codigo: '03',
    descripcion: 'COLON',
    municipio: '25',
    departamento: '05',
    activo: true,
  ),
  Distrito(
    codigo: '07',
    descripcion: 'EL TRANSITO',
    municipio: '23',
    departamento: '12',
    activo: true,
  ),
  Distrito(
    codigo: '12',
    descripcion: 'SANTIAGO DE LA FRONTERA',
    municipio: '17',
    departamento: '02',
    activo: true,
  ),
  Distrito(
    codigo: '03',
    descripcion: 'JERUSALEN',
    municipio: '24',
    departamento: '08',
    activo: true,
  ),
  Distrito(
    codigo: '04',
    descripcion: 'CHAPELTIQUE',
    municipio: '21',
    departamento: '12',
    activo: true,
  ),
  Distrito(
    codigo: '11',
    descripcion: 'NVO EDEN S JUAN',
    municipio: '21',
    departamento: '12',
    activo: true,
  ),
  Distrito(
    codigo: '04',
    descripcion: 'COMASAGUA',
    municipio: '28',
    departamento: '05',
    activo: true,
  ),
  Distrito(
    codigo: '01',
    descripcion: 'CANDELARIA DE LA FRONTERA',
    municipio: '17',
    departamento: '02',
    activo: true,
  ),
  Distrito(
    codigo: '03',
    descripcion: 'CHALCHUAPA',
    municipio: '17',
    departamento: '02',
    activo: true,
  ),
  Distrito(
    codigo: '02',
    descripcion: 'COATEPEQUE',
    municipio: '16',
    departamento: '02',
    activo: true,
  ),
  Distrito(
    codigo: '10',
    descripcion: 'SANTA ANA',
    municipio: '15',
    departamento: '02',
    activo: true,
  ),
  Distrito(
    codigo: '09',
    descripcion: 'NEJAPA',
    municipio: '21',
    departamento: '06',
    activo: true,
  ),
  Distrito(
    codigo: '14',
    descripcion: 'SAN MIGUEL TEPEZONTES',
    municipio: '24',
    departamento: '08',
    activo: true,
  ),
  Distrito(
    codigo: '08',
    descripcion: 'JICALAPA',
    municipio: '27',
    departamento: '05',
    activo: true,
  ),
  Distrito(
    codigo: '11',
    descripcion: 'SANTA TECLA',
    municipio: '28',
    departamento: '05',
    activo: true,
  ),
  Distrito(
    codigo: '09',
    descripcion: 'LA LIBERTAD',
    municipio: '27',
    departamento: '05',
    activo: true,
  ),
  Distrito(
    codigo: '01',
    descripcion: 'APASTEPEQUE',
    municipio: '14',
    departamento: '10',
    activo: true,
  ),
  Distrito(
    codigo: '06',
    descripcion: 'MASAHUAT',
    municipio: '14',
    departamento: '02',
    activo: true,
  ),
  Distrito(
    codigo: '07',
    descripcion: 'METAPÁN',
    municipio: '14',
    departamento: '02',
    activo: true,
  ),
  Distrito(
    codigo: '06',
    descripcion: 'SENSUNTEPEQUE',
    municipio: '10',
    departamento: '09',
    activo: true,
  ),
  Distrito(
    codigo: '01',
    descripcion: 'ALEGRIA',
    municipio: '24',
    departamento: '11',
    activo: true,
  ),
  Distrito(
    codigo: '14',
    descripcion: 'STA C MICHAPA',
    municipio: '18',
    departamento: '07',
    activo: true,
  ),
  Distrito(
    codigo: '04',
    descripcion: 'CITALA',
    municipio: '34',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '03',
    descripcion: 'AZACUALPA',
    municipio: '36',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '13',
    descripcion: 'SAN ANT D MOSCO',
    municipio: '21',
    departamento: '12',
    activo: true,
  ),
  Distrito(
    codigo: '11',
    descripcion: 'TACUBA',
    municipio: '14',
    departamento: '01',
    activo: true,
  ),
  Distrito(
    codigo: '01',
    descripcion: 'ARAMBALA',
    municipio: '27',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '08',
    descripcion: 'DULCE NOMBRE DE MARIA',
    municipio: '35',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '22',
    descripcion: 'ZARAGOZA',
    municipio: '26',
    departamento: '05',
    activo: true,
  ),
  Distrito(
    codigo: '13',
    descripcion: 'VERAPAZ',
    municipio: '15',
    departamento: '10',
    activo: true,
  ),
  Distrito(
    codigo: '15',
    descripcion: 'NOMBRE DE JESUS',
    municipio: '36',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '14',
    descripcion: 'PTO EL TRIUNFO',
    municipio: '26',
    departamento: '11',
    activo: true,
  ),
  Distrito(
    codigo: '15',
    descripcion: 'SUCHITOTO',
    municipio: '17',
    departamento: '07',
    activo: true,
  ),
  Distrito(
    codigo: '14',
    descripcion: 'LAS VUELTAS',
    municipio: '36',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '09',
    descripcion: 'SN FCO CHINAMEC',
    municipio: '23',
    departamento: '08',
    activo: true,
  ),
  Distrito(
    codigo: '13',
    descripcion: 'SACACOYO',
    municipio: '25',
    departamento: '05',
    activo: true,
  ),
  Distrito(
    codigo: '26',
    descripcion: 'SAN I LABRADOR',
    municipio: '36',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '17',
    descripcion: 'SAN P TACACHICO',
    municipio: '23',
    departamento: '05',
    activo: true,
  ),
  Distrito(
    codigo: '23',
    descripcion: 'USULUTAN',
    municipio: '25',
    departamento: '11',
    activo: true,
  ),
  Distrito(
    codigo: '21',
    descripcion: 'TEPECOYO',
    municipio: '25',
    departamento: '05',
    activo: true,
  ),
  Distrito(
    codigo: '01',
    descripcion: 'CUYULTITAN',
    municipio: '23',
    departamento: '08',
    activo: true,
  ),
  Distrito(
    codigo: '04',
    descripcion: 'CUSCATANCINGO',
    municipio: '23',
    departamento: '06',
    activo: true,
  ),
  Distrito(
    codigo: '03',
    descripcion: 'EL CARMEN',
    municipio: '18',
    departamento: '07',
    activo: true,
  ),
  Distrito(
    codigo: '14',
    descripcion: 'SN J VILLANUEVA',
    municipio: '26',
    departamento: '05',
    activo: true,
  ),
  Distrito(
    codigo: '18',
    descripcion: 'OJOS DE AGUA',
    municipio: '36',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '19',
    descripcion: 'POTONICO',
    municipio: '36',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '20',
    descripcion: 'SAN ANT LA CRUZ',
    municipio: '36',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '10',
    descripcion: 'PANCHIMALCO',
    municipio: '24',
    departamento: '06',
    activo: true,
  ),
  Distrito(
    codigo: '02',
    descripcion: 'ARMENIA',
    municipio: '19',
    departamento: '03',
    activo: true,
  ),
  Distrito(
    codigo: '02',
    descripcion: 'COJUTEPEQUE',
    municipio: '18',
    departamento: '07',
    activo: true,
  ),
  Distrito(
    codigo: '19',
    descripcion: 'TALNIQUE',
    municipio: '25',
    departamento: '05',
    activo: true,
  ),
  Distrito(
    codigo: '08',
    descripcion: 'JIQUILISCO',
    municipio: '26',
    departamento: '11',
    activo: true,
  ),
  Distrito(
    codigo: '07',
    descripcion: 'SAN B PERULAPIA',
    municipio: '17',
    departamento: '07',
    activo: true,
  ),
  Distrito(
    codigo: '12',
    descripcion: 'TEPETITAN',
    municipio: '15',
    departamento: '10',
    activo: true,
  ),
  Distrito(
    codigo: '08',
    descripcion: 'SAN CRISTOBAL',
    municipio: '18',
    departamento: '07',
    activo: true,
  ),
  Distrito(
    codigo: '20',
    descripcion: 'TEOTEPEQUE',
    municipio: '27',
    departamento: '05',
    activo: true,
  ),
  Distrito(
    codigo: '04',
    descripcion: 'CUISNAHUAT',
    municipio: '19',
    departamento: '03',
    activo: true,
  ),
  Distrito(
    codigo: '11',
    descripcion: 'SAN RAF CEDROS',
    municipio: '18',
    departamento: '07',
    activo: true,
  ),
  Distrito(
    codigo: '12',
    descripcion: 'SAN RAMON',
    municipio: '18',
    departamento: '07',
    activo: true,
  ),
  Distrito(
    codigo: '21',
    descripcion: 'ZACATECOLUCA',
    municipio: '25',
    departamento: '08',
    activo: true,
  ),
  Distrito(
    codigo: '07',
    descripcion: 'SAN ILDEFONSO',
    municipio: '14',
    departamento: '10',
    activo: true,
  ),
  Distrito(
    codigo: '17',
    descripcion: 'SAN DIONISIO',
    municipio: '25',
    departamento: '11',
    activo: true,
  ),
  Distrito(
    codigo: '08',
    descripcion: 'SAN EMIGDIO',
    municipio: '24',
    departamento: '08',
    activo: true,
  ),
  Distrito(
    codigo: '12',
    descripcion: 'LA PALMA',
    municipio: '34',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '05',
    descripcion: 'OLOCUILTA',
    municipio: '23',
    departamento: '08',
    activo: true,
  ),
  Distrito(
    codigo: '08',
    descripcion: 'MEJICANOS',
    municipio: '23',
    departamento: '06',
    activo: true,
  ),
  Distrito(
    codigo: '11',
    descripcion: 'TECOLUCA',
    municipio: '15',
    departamento: '10',
    activo: true,
  ),
  Distrito(
    codigo: '03',
    descripcion: 'CALUCO',
    municipio: '19',
    departamento: '03',
    activo: true,
  ),
  Distrito(
    codigo: '06',
    descripcion: 'PARAISO OSORIO',
    municipio: '24',
    departamento: '08',
    activo: true,
  ),
  Distrito(
    codigo: '25',
    descripcion: 'SAN IGNACIO',
    municipio: '34',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '06',
    descripcion: 'EL DIVISADERO',
    municipio: '28',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '06',
    descripcion: 'GUAZAPA',
    municipio: '20',
    departamento: '06',
    activo: true,
  ),
  Distrito(
    codigo: '18',
    descripcion: 'TAMANIQUE',
    municipio: '27',
    departamento: '05',
    activo: true,
  ),
  Distrito(
    codigo: '18',
    descripcion: 'SANTA ELENA',
    municipio: '25',
    departamento: '11',
    activo: true,
  ),
  Distrito(
    codigo: '08',
    descripcion: 'GUALOCOCTI',
    municipio: '28',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '05',
    descripcion: 'STA ISABEL ISHUATÁN',
    municipio: '19',
    departamento: '03',
    activo: true,
  ),
  Distrito(
    codigo: '01',
    descripcion: 'CANDELARIA',
    municipio: '18',
    departamento: '07',
    activo: true,
  ),
  Distrito(
    codigo: '10',
    descripcion: 'NUEVO CUSCATLAN',
    municipio: '26',
    departamento: '05',
    activo: true,
  ),
  Distrito(
    codigo: '21',
    descripcion: 'SAN ANT RANCHOS',
    municipio: '36',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '17',
    descripcion: 'SAN R OBRAJUELO',
    municipio: '25',
    departamento: '08',
    activo: true,
  ),
  Distrito(
    codigo: '08',
    descripcion: 'SAN LORENZO',
    municipio: '14',
    departamento: '10',
    activo: true,
  ),
  Distrito(
    codigo: '06',
    descripcion: 'ORAT CONCEPCION',
    municipio: '17',
    departamento: '07',
    activo: true,
  ),
  Distrito(
    codigo: '17',
    descripcion: 'NUEVA TRINIDAD',
    municipio: '36',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '16',
    descripcion: 'TENANCINGO',
    municipio: '18',
    departamento: '07',
    activo: true,
  ),
  Distrito(
    codigo: '07',
    descripcion: 'JAYAQUE',
    municipio: '25',
    departamento: '05',
    activo: true,
  ),
  Distrito(
    codigo: '10',
    descripcion: 'SAN VICENTE',
    municipio: '15',
    departamento: '10',
    activo: true,
  ),
  Distrito(
    codigo: '09',
    descripcion: 'GUATAJIAGUA',
    municipio: '28',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '10',
    descripcion: 'SAN P PERULAPAN',
    municipio: '17',
    departamento: '07',
    activo: true,
  ),
  Distrito(
    codigo: '20',
    descripcion: 'SANTA MARIA',
    municipio: '25',
    departamento: '11',
    activo: true,
  ),
  Distrito(
    codigo: '12',
    descripcion: 'JOCORO',
    municipio: '28',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '04',
    descripcion: 'EL ROSARIO',
    municipio: '18',
    departamento: '07',
    activo: true,
  ),
  Distrito(
    codigo: '13',
    descripcion: 'STA C ANALQUITO',
    municipio: '18',
    departamento: '07',
    activo: true,
  ),
  Distrito(
    codigo: '02',
    descripcion: 'BERLIN',
    municipio: '24',
    departamento: '11',
    activo: true,
  ),
  Distrito(
    codigo: '09',
    descripcion: 'LISLIQUE',
    municipio: '19',
    departamento: '14',
    activo: true,
  ),
  Distrito(
    codigo: '05',
    descripcion: 'MONTE SAN JUAN',
    municipio: '18',
    departamento: '07',
    activo: true,
  ),
  Distrito(
    codigo: '12',
    descripcion: 'SAN JUAN TEPEZONTES',
    municipio: '24',
    departamento: '08',
    activo: true,
  ),
  Distrito(
    codigo: '03',
    descripcion: 'SAN CAY ISTEPEQ',
    municipio: '15',
    departamento: '10',
    activo: true,
  ),
  Distrito(
    codigo: '16',
    descripcion: 'SONZACATE',
    municipio: '18',
    departamento: '03',
    activo: true,
  ),
  Distrito(
    codigo: '02',
    descripcion: 'EL ROSARIO',
    municipio: '24',
    departamento: '08',
    activo: true,
  ),
  Distrito(
    codigo: '15',
    descripcion: 'SAN JUAN OPICO',
    municipio: '24',
    departamento: '05',
    activo: true,
  ),
  Distrito(
    codigo: '13',
    descripcion: 'LOLOTIQUILLO',
    municipio: '28',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '07',
    descripcion: 'EL ROSARIO',
    municipio: '27',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '04',
    descripcion: 'CHILANGA',
    municipio: '28',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '16',
    descripcion: 'SAN PEDRO NONUALCO',
    municipio: '24',
    departamento: '08',
    activo: true,
  ),
  Distrito(
    codigo: '18',
    descripcion: 'STA MA OSTUMA',
    municipio: '24',
    departamento: '08',
    activo: true,
  ),
  Distrito(
    codigo: '10',
    descripcion: 'SAN J NONUALCO',
    municipio: '25',
    departamento: '08',
    activo: true,
  ),
  Distrito(
    codigo: '02',
    descripcion: 'GUADALUPE',
    municipio: '15',
    departamento: '10',
    activo: true,
  ),
  Distrito(
    codigo: '19',
    descripcion: 'SAN FCO GOTERA',
    municipio: '28',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '03',
    descripcion: 'COMACARAN',
    municipio: '22',
    departamento: '12',
    activo: true,
  ),
  Distrito(
    codigo: '07',
    descripcion: 'CHALATENANGO',
    municipio: '36',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '04',
    descripcion: 'SANTA CLARA',
    municipio: '14',
    departamento: '10',
    activo: true,
  ),
  Distrito(
    codigo: '01',
    descripcion: 'CINQUERA',
    municipio: '11',
    departamento: '09',
    activo: true,
  ),
  Distrito(
    codigo: '12',
    descripcion: 'NUEVA GRANADA',
    municipio: '24',
    departamento: '11',
    activo: true,
  ),
  Distrito(
    codigo: '04',
    descripcion: 'CONCEP BATRES',
    municipio: '25',
    departamento: '11',
    activo: true,
  ),
  Distrito(
    codigo: '10',
    descripcion: 'MEANG DEL GOLFO',
    municipio: '20',
    departamento: '14',
    activo: true,
  ),
  Distrito(
    codigo: '17',
    descripcion: 'SAN CARLOS',
    municipio: '28',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '01',
    descripcion: 'CAROLINA',
    municipio: '21',
    departamento: '12',
    activo: true,
  ),
  Distrito(
    codigo: '17',
    descripcion: 'SAN MIGUEL',
    municipio: '22',
    departamento: '12',
    activo: true,
  ),
  Distrito(
    codigo: '05',
    descripcion: 'EL CARMEN',
    municipio: '20',
    departamento: '14',
    activo: true,
  ),
  Distrito(
    codigo: '18',
    descripcion: 'SAN FERNANDO',
    municipio: '27',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '24',
    descripcion: 'SAN FRANCISCO MORAZAN',
    municipio: '35',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '06',
    descripcion: 'SN EST CATARINA',
    municipio: '14',
    departamento: '10',
    activo: true,
  ),
  Distrito(
    codigo: '28',
    descripcion: 'SAN JOSE FLORES',
    municipio: '36',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '06',
    descripcion: 'EREGUAYQUIN',
    municipio: '25',
    departamento: '11',
    activo: true,
  ),
  Distrito(
    codigo: '16',
    descripcion: 'SANTA ROSA LIMA',
    municipio: '19',
    departamento: '14',
    activo: true,
  ),
  Distrito(
    codigo: '11',
    descripcion: 'SANTA ROSA GUACHIPILÍN',
    municipio: '14',
    departamento: '02',
    activo: true,
  ),
  Distrito(
    codigo: '07',
    descripcion: 'JUAYÚA',
    municipio: '17',
    departamento: '03',
    activo: true,
  ),
  Distrito(
    codigo: '06',
    descripcion: 'IZALCO',
    municipio: '19',
    departamento: '03',
    activo: true,
  ),
  Distrito(
    codigo: '18',
    descripcion: 'TONACATEPEQUE',
    municipio: '22',
    departamento: '06',
    activo: true,
  ),
  Distrito(
    codigo: '22',
    descripcion: 'SN LUIS LA HERR',
    municipio: '24',
    departamento: '08',
    activo: true,
  ),
  Distrito(
    codigo: '06',
    descripcion: 'CONCEPCION QUEZALTEPEQUE',
    municipio: '36',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '15',
    descripcion: 'OSICALA',
    municipio: '28',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '14',
    descripcion: 'SAN GERARDO',
    municipio: '21',
    departamento: '12',
    activo: true,
  ),
  Distrito(
    codigo: '20',
    descripcion: 'ULUAZAPA',
    municipio: '22',
    departamento: '12',
    activo: true,
  ),
  Distrito(
    codigo: '14',
    descripcion: 'SAN ALEJO',
    municipio: '20',
    departamento: '14',
    activo: true,
  ),
  Distrito(
    codigo: '12',
    descripcion: 'PASAQUINA',
    municipio: '19',
    departamento: '14',
    activo: true,
  ),
  Distrito(
    codigo: '10',
    descripcion: 'SALCOATITÁN',
    municipio: '17',
    departamento: '03',
    activo: true,
  ),
  Distrito(
    codigo: '31',
    descripcion: 'SAN RAFAEL',
    municipio: '35',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '15',
    descripcion: 'SONSONATE',
    municipio: '18',
    departamento: '03',
    activo: true,
  ),
  Distrito(
    codigo: '08',
    descripcion: 'LA UNION',
    municipio: '20',
    departamento: '14',
    activo: true,
  ),
  Distrito(
    codigo: '06',
    descripcion: 'EL SAUCE',
    municipio: '19',
    departamento: '14',
    activo: true,
  ),
  Distrito(
    codigo: '11',
    descripcion: 'SAN ANTONIO DEL MONTE',
    municipio: '18',
    departamento: '03',
    activo: true,
  ),
  Distrito(
    codigo: '12',
    descripcion: 'SAN JULIAN',
    municipio: '19',
    departamento: '03',
    activo: true,
  ),
  Distrito(
    codigo: '13',
    descripcion: 'STA C MASAHUAT',
    municipio: '17',
    departamento: '03',
    activo: true,
  ),
  Distrito(
    codigo: '19',
    descripcion: 'CIUDAD DELGADO',
    municipio: '23',
    departamento: '06',
    activo: true,
  ),
  Distrito(
    codigo: '20',
    descripcion: 'TAPALHUACA',
    municipio: '23',
    departamento: '08',
    activo: true,
  ),
  Distrito(
    codigo: '05',
    descripcion: 'SANTO DOMINGO',
    municipio: '14',
    departamento: '10',
    activo: true,
  ),
  Distrito(
    codigo: '27',
    descripcion: 'SAN J CANCASQUE',
    municipio: '36',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '13',
    descripcion: 'OZATLAN',
    municipio: '25',
    departamento: '11',
    activo: true,
  ),
  Distrito(
    codigo: '04',
    descripcion: 'CONCHAGUA',
    municipio: '20',
    departamento: '14',
    activo: true,
  ),
  Distrito(
    codigo: '11',
    descripcion: 'JOCOAITIQUE',
    municipio: '27',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '22',
    descripcion: 'SENSEMBRA',
    municipio: '28',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '26',
    descripcion: 'YOLOAIQUIN',
    municipio: '28',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '14',
    descripcion: 'SAN SALVADOR',
    municipio: '23',
    departamento: '06',
    activo: true,
  ),
  Distrito(
    codigo: '02',
    descripcion: 'ARCATAO',
    municipio: '36',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '17',
    descripcion: 'YAYANTIQUE',
    municipio: '20',
    departamento: '14',
    activo: true,
  ),
  Distrito(
    codigo: '24',
    descripcion: 'TOROLA',
    municipio: '27',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '13',
    descripcion: 'POLOROS',
    municipio: '19',
    departamento: '14',
    activo: true,
  ),
  Distrito(
    codigo: '32',
    descripcion: 'SANTA RITA',
    municipio: '35',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '14',
    descripcion: 'SANTO DOMINGO GUZMAN',
    municipio: '18',
    departamento: '03',
    activo: true,
  ),
  Distrito(
    codigo: '09',
    descripcion: 'NAHULINGO',
    municipio: '18',
    departamento: '03',
    activo: true,
  ),
  Distrito(
    codigo: '20',
    descripcion: 'SAN ISIDRO',
    municipio: '27',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '23',
    descripcion: 'SAN FRANCISCO LEMPA',
    municipio: '36',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '09',
    descripcion: 'DOLORES',
    municipio: '10',
    departamento: '09',
    activo: true,
  ),
  Distrito(
    codigo: '19',
    descripcion: 'SAN FCO JAVIER',
    municipio: '26',
    departamento: '11',
    activo: true,
  ),
  Distrito(
    codigo: '08',
    descripcion: 'LOLOTIQUE',
    municipio: '23',
    departamento: '12',
    activo: true,
  ),
  Distrito(
    codigo: '12',
    descripcion: 'QUEZALTEPEQUE',
    municipio: '23',
    departamento: '05',
    activo: true,
  ),
  Distrito(
    codigo: '15',
    descripcion: 'SAN PEDRO MASAHUAT',
    municipio: '23',
    departamento: '08',
    activo: true,
  ),
  Distrito(
    codigo: '19',
    descripcion: 'STGO NONUALCO',
    municipio: '24',
    departamento: '08',
    activo: true,
  ),
  Distrito(
    codigo: '16',
    descripcion: 'NUEVA CONCEPCION',
    municipio: '35',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '04',
    descripcion: 'JUTIAPA',
    municipio: '11',
    departamento: '09',
    activo: true,
  ),
  Distrito(
    codigo: '10',
    descripcion: 'NUEVA GUADALUPE',
    municipio: '23',
    departamento: '12',
    activo: true,
  ),
  Distrito(
    codigo: '05',
    descripcion: 'CHINAMECA',
    municipio: '23',
    departamento: '12',
    activo: true,
  ),
  Distrito(
    codigo: '18',
    descripcion: 'SAN RAF ORIENTE',
    municipio: '23',
    departamento: '12',
    activo: true,
  ),
  Distrito(
    codigo: '04',
    descripcion: 'MERCED LA CEIBA',
    municipio: '24',
    departamento: '08',
    activo: true,
  ),
  Distrito(
    codigo: '22',
    descripcion: 'TECAPAN',
    municipio: '25',
    departamento: '11',
    activo: true,
  ),
  Distrito(
    codigo: '03',
    descripcion: 'ILOBASCO',
    municipio: '11',
    departamento: '09',
    activo: true,
  ),
  Distrito(
    codigo: '19',
    descripcion: 'SESORI',
    municipio: '21',
    departamento: '12',
    activo: true,
  ),
  Distrito(
    codigo: '25',
    descripcion: 'YAMABAL',
    municipio: '28',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '02',
    descripcion: 'CIUDAD ARCE',
    municipio: '24',
    departamento: '05',
    activo: true,
  ),
  Distrito(
    codigo: '08',
    descripcion: 'NAHUIZALCO',
    municipio: '17',
    departamento: '03',
    activo: true,
  ),
  Distrito(
    codigo: '02',
    descripcion: 'CACAOPERA',
    municipio: '27',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '13',
    descripcion: 'SAN LUIS TALPA',
    municipio: '23',
    departamento: '08',
    activo: true,
  ),
  Distrito(
    codigo: '18',
    descripcion: 'YUCUAIQUIN',
    municipio: '20',
    departamento: '14',
    activo: true,
  ),
  Distrito(
    codigo: '03',
    descripcion: 'CALIFORNIA',
    municipio: '25',
    departamento: '11',
    activo: true,
  ),
  Distrito(
    codigo: '02',
    descripcion: 'CIUDAD BARRIOS',
    municipio: '21',
    departamento: '12',
    activo: true,
  ),
  Distrito(
    codigo: '22',
    descripcion: 'SAN FERNANDO',
    municipio: '35',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '08',
    descripcion: 'VICTORIA',
    municipio: '10',
    departamento: '09',
    activo: true,
  ),
  Distrito(
    codigo: '07',
    descripcion: 'TEJUTEPEQUE',
    municipio: '11',
    departamento: '09',
    activo: true,
  ),
  Distrito(
    codigo: '09',
    descripcion: 'MONCAGUA',
    municipio: '22',
    departamento: '12',
    activo: true,
  ),
  Distrito(
    codigo: '16',
    descripcion: 'SAN LUIS REINA',
    municipio: '21',
    departamento: '12',
    activo: true,
  ),
  Distrito(
    codigo: '07',
    descripcion: 'INTIPUCA',
    municipio: '20',
    departamento: '14',
    activo: true,
  ),
  Distrito(
    codigo: '13',
    descripcion: 'SAN MARTIN',
    municipio: '22',
    departamento: '06',
    activo: true,
  ),
  Distrito(
    codigo: '16',
    descripcion: 'SAN MATIAS',
    municipio: '23',
    departamento: '05',
    activo: true,
  ),
  Distrito(
    codigo: '09',
    descripcion: 'SAN SEBASTIAN',
    municipio: '14',
    departamento: '10',
    activo: true,
  ),
  Distrito(
    codigo: '09',
    descripcion: 'JUCUAPA',
    municipio: '24',
    departamento: '11',
    activo: true,
  ),
  Distrito(
    codigo: '15',
    descripcion: 'SAN JORGE',
    municipio: '23',
    departamento: '12',
    activo: true,
  ),
  Distrito(
    codigo: '11',
    descripcion: 'LA LAGUNA',
    municipio: '36',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '10',
    descripcion: 'JUCUARAN',
    municipio: '25',
    departamento: '11',
    activo: true,
  ),
  Distrito(
    codigo: '11',
    descripcion: 'NUEVA ESPARTA',
    municipio: '19',
    departamento: '14',
    activo: true,
  ),
  Distrito(
    codigo: '10',
    descripcion: 'JOATECA',
    municipio: '27',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '11',
    descripcion: 'SAN JUAN TALPA',
    municipio: '23',
    departamento: '08',
    activo: true,
  ),
  Distrito(
    codigo: '01',
    descripcion: 'ACAJUTLA',
    municipio: '20',
    departamento: '03',
    activo: true,
  ),
  Distrito(
    codigo: '16',
    descripcion: 'PERQUIN',
    municipio: '27',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '01',
    descripcion: 'ANAMOROS',
    municipio: '19',
    departamento: '14',
    activo: true,
  ),
  Distrito(
    codigo: '09',
    descripcion: 'EL CARRIZAL',
    municipio: '36',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '16',
    descripcion: 'SN BUENAVENTURA',
    municipio: '24',
    departamento: '11',
    activo: true,
  ),
  Distrito(
    codigo: '11',
    descripcion: 'MERCEDES UMAÑA',
    municipio: '24',
    departamento: '11',
    activo: true,
  ),
  Distrito(
    codigo: '15',
    descripcion: 'SAN AGUSTIN',
    municipio: '26',
    departamento: '11',
    activo: true,
  ),
  Distrito(
    codigo: '03',
    descripcion: 'CORINTO',
    municipio: '27',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '12',
    descripcion: 'SAN MARCOS',
    municipio: '24',
    departamento: '06',
    activo: true,
  ),
  Distrito(
    codigo: '16',
    descripcion: 'SANTO TOMAS',
    municipio: '24',
    departamento: '06',
    activo: true,
  ),
  Distrito(
    codigo: '07',
    descripcion: 'SN ANT MASAHUAT',
    municipio: '24',
    departamento: '08',
    activo: true,
  ),
  Distrito(
    codigo: '02',
    descripcion: 'BOLIVAR',
    municipio: '19',
    departamento: '14',
    activo: true,
  ),
  Distrito(
    codigo: '21',
    descripcion: 'STGO DE MARIA',
    municipio: '24',
    departamento: '11',
    activo: true,
  ),
  Distrito(
    codigo: '21',
    descripcion: 'SAN SIMON',
    municipio: '28',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '05',
    descripcion: 'DELIC DE CONCEP',
    municipio: '28',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '15',
    descripcion: 'SAN JOSE',
    municipio: '19',
    departamento: '14',
    activo: true,
  ),
  Distrito(
    codigo: '11',
    descripcion: 'ROSARIO DE MORA',
    municipio: '24',
    departamento: '06',
    activo: true,
  ),
  Distrito(
    codigo: '15',
    descripcion: 'STG TEXACUANGOS',
    municipio: '24',
    departamento: '06',
    activo: true,
  ),
  Distrito(
    codigo: '17',
    descripcion: 'SOYAPANGO',
    municipio: '22',
    departamento: '06',
    activo: true,
  ),
  Distrito(
    codigo: '03',
    descripcion: 'CONCEP DE OTE',
    municipio: '19',
    departamento: '14',
    activo: true,
  ),
  Distrito(
    codigo: '05',
    descripcion: 'COMALAPA',
    municipio: '36',
    departamento: '04',
    activo: true,
  ),
  Distrito(
    codigo: '14',
    descripcion: 'MEANGUERA',
    municipio: '27',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '06',
    descripcion: 'CHIRILAGUA',
    municipio: '22',
    departamento: '12',
    activo: true,
  ),
  Distrito(
    codigo: '12',
    descripcion: 'QUELEPA',
    municipio: '22',
    departamento: '12',
    activo: true,
  ),
  Distrito(
    codigo: '23',
    descripcion: 'SOCIEDAD',
    municipio: '28',
    departamento: '13',
    activo: true,
  ),
  Distrito(
    codigo: '00',
    descripcion: 'Otro (Para extranjeros)',
    municipio: '00',
    departamento: '00',
    activo: true,
  ),
];

/// Retorna los distritos filtrados por municipio y departamento
List<Distrito> getDistritosPorMunicipioYDepartamento(
  String codigoMunicipio,
  String codigoDepartamento,
) {
  // Extraer solo el código numérico del departamento (ej: "02" de "02 - Santa Ana")
  final depCodigo = codigoDepartamento.split(' - ').first;
  // Extraer solo el código numérico del municipio (ej: "15" de "15 - SANTA ANA CENTRO")
  final munCodigo = codigoMunicipio.split(' - ').first;

  return kDistritos
      .where(
        (d) =>
            d.departamento == depCodigo && d.municipio == munCodigo && d.activo,
      )
      .toList();
}
