// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-sxiiXRqSrhlGq8k2B7PAUk_J2YWsrDQ',
    appId: '1:30028285167:web:ae7e231de34f8a6c47871a',
    messagingSenderId: '30028285167',
    projectId: 'facturacion-app-sv',
    authDomain: 'facturacion-app-sv.firebaseapp.com',
    storageBucket: 'facturacion-app-sv.firebasestorage.app',
    measurementId: 'G-GXVGMGQTW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVWYdjN4eznTD6Vi7gPD5H7qYza42q8TE',
    appId: '1:30028285167:android:5401ba3d16b7b61347871a',
    messagingSenderId: '30028285167',
    projectId: 'facturacion-app-sv',
    storageBucket: 'facturacion-app-sv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcnXBWOVPj_4dsey81l9C1cxIKVoiPZ84',
    appId: '1:30028285167:ios:92f52b1f781c2e8b47871a',
    messagingSenderId: '30028285167',
    projectId: 'facturacion-app-sv',
    storageBucket: 'facturacion-app-sv.firebasestorage.app',
    iosBundleId: 'com.facturacion.sv.appFactura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcnXBWOVPj_4dsey81l9C1cxIKVoiPZ84',
    appId: '1:30028285167:ios:92f52b1f781c2e8b47871a',
    messagingSenderId: '30028285167',
    projectId: 'facturacion-app-sv',
    storageBucket: 'facturacion-app-sv.firebasestorage.app',
    iosBundleId: 'com.facturacion.sv.appFactura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-sxiiXRqSrhlGq8k2B7PAUk_J2YWsrDQ',
    appId: '1:30028285167:web:127396cba51d1d0147871a',
    messagingSenderId: '30028285167',
    projectId: 'facturacion-app-sv',
    authDomain: 'facturacion-app-sv.firebaseapp.com',
    storageBucket: 'facturacion-app-sv.firebasestorage.app',
    measurementId: 'G-TE5FE1B9CK',
  );
}